package grbl

import (
	"errors"
	"fmt"
	"strings"

	"github.com/jroimartin/gocui"
)

type PromptView struct {
	name, prompt string
	enterFn      func(gui *gocui.Gui, command string) error
}

func NewPromptView(name, prompt string, enterFn func(gui *gocui.Gui, command string) error) *PromptView {
	return &PromptView{
		name:    name,
		prompt:  prompt,
		enterFn: enterFn,
	}
}

//gocyclo:ignore
func (p *PromptView) editorFn(view *gocui.View, key gocui.Key, ch rune, mod gocui.Modifier) {
	// TODO Implement a state machine to interpret the CSI sequence generated by the terminal. This enables
	// support for combinations such as Ctrl-LeftArrow to work.

	switch {
	// Movement
	case key == gocui.KeyHome || key == gocui.KeyCtrlA:
		if err := view.SetCursor(len(p.prompt), 0); err != nil {
			panic(err)
		}
		if err := view.SetOrigin(0, 0); err != nil {
			panic(err)
		}
	case key == gocui.KeyEnd || key == gocui.KeyCtrlE:
		line := strings.TrimSuffix(view.Buffer(), "\n")
		if err := view.SetCursor(len(line), 0); err != nil {
			panic(err)
		}
	case key == gocui.KeyArrowLeft || key == gocui.KeyCtrlB:
		if cx, _ := view.Cursor(); cx > len(p.prompt) {
			view.MoveCursor(-1, 0, false)
		}
	case key == gocui.KeyArrowRight || key == gocui.KeyCtrlF:
		view.MoveCursor(1, 0, false)
	// TODO	Alt + B or Ctrl + ←	Move backward one word.
	// TODO Alt + F or Ctrl + →	Move forward one word.

	// Editing
	case key == gocui.KeyDelete || key == gocui.KeyCtrlD:
		view.EditDelete(false)
	case key == gocui.KeyBackspace || key == gocui.KeyBackspace2 || key == gocui.KeyCtrlH:
		if cx, _ := view.Cursor(); cx > len(p.prompt) {
			view.EditDelete(true)
		}
	// TODO Ctrl + U	Delete from the cursor to the beginning of the line (cut).
	// TODO Ctrl + K	Delete from the cursor to the end of the line (cut).
	// TODO Ctrl + W	Delete the word before the cursor (cut).
	// TODO Alt + D	Delete the word after the cursor (cut).
	// TODO Ctrl + Y	Paste the last deleted text ("yank").
	// TODO Ctrl + _	Undo the last change.
	// TODO Alt + T	Transpose the current word with the previous word.
	// TODO Ctrl + T	Transpose the character under the cursor with the previous one.
	case ch != 0 && mod == 0:
		view.EditWrite(ch)
	case key == gocui.KeySpace:
		view.EditWrite(' ')
	case key == gocui.KeyInsert:
		view.Overwrite = !view.Overwrite

		// History

		// TODO Ctrl + P or ↑	Fetch the previous command from history.
		// TODO Ctrl + N or ↓	Fetch the next command from history.
		// TODO Ctrl + R	Start a reverse search through history as you type.
		// TODO Alt + . or Esc + .	Insert the last argument of the previous command.

		// Control

		// TODO Ctrl + L	Clear the screen.
		// TODO Ctrl + C	Interrupt the current command (sends SIGINT).
		// TODO Ctrl + Z	Suspend the current command (sends SIGTSTP).
		// TODO Ctrl + D	Exit the shell (if the line is empty).

	}
}

func (p *PromptView) GetManagerFn(gui *gocui.Gui, x0, y0, x1, y1 int) func(gui *gocui.Gui) error {
	return func(gui *gocui.Gui) error {
		if view, err := gui.SetView(p.name, x0, y0, x1, y1); err != nil {
			if err != gocui.ErrUnknownView {
				return err
			}
			view.Editable = true
			view.Editor = gocui.EditorFunc(p.editorFn)
			view.Wrap = false
			fmt.Fprint(view, p.prompt)
			view.SetCursor(len(p.prompt), 0)
			return nil
		}
		return nil
	}
}

func (p *PromptView) handleKeyBindEnter(gui *gocui.Gui, view *gocui.View) (err error) {
	buff := view.Buffer()

	command := ""
	if len(buff) > len(p.prompt) {
		command = strings.TrimSuffix(buff[len(p.prompt):], "\n")
	}

	if len(command) == 0 {
		return nil
	}

	if enterFnErr := p.enterFn(gui, command); enterFnErr != nil {
		err = errors.Join(err, enterFnErr)
	}

	view.Clear()

	fmt.Fprint(view, p.prompt)

	if setCursorErr := view.SetCursor(len(p.prompt), 0); setCursorErr != nil {
		err = errors.Join(err, setCursorErr)
	}

	if setOriginErr := view.SetOrigin(0, 0); setOriginErr != nil {
		err = errors.Join(err, setOriginErr)
	}

	return err
}

func (p *PromptView) InitKeybindings(gui *gocui.Gui) error {
	// Enter
	if err := gui.SetKeybinding(p.name, gocui.KeyEnter, gocui.ModNone, p.handleKeyBindEnter); err != nil {
		return err
	}

	return nil
}
