(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: Back_Post_Mask.nc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Friday, 31 October 2025 at 16:13)



   (Move to maintenance position)
 G21 G90 G53 F200 Z-1
 G21 G90 G17 F200 X181.80142506248126
 G21 G90 G53 F200 Y0 Z-1
				G17
				
  (########## ACTION ##########)
 (Clean the chips)
 M0
 
 
 
